-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE CHECK (slug::text ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'::text),
  recruiter_id uuid NOT NULL,
  logo_storage_path character varying,
  banner_storage_path character varying,
  primary_color character varying DEFAULT '#0066CC'::character varying,
  secondary_color character varying DEFAULT '#FF6B6B'::character varying,
  accent_color character varying DEFAULT '#FFD93D'::character varying,
  font_family character varying DEFAULT 'inter'::character varying,
  mission_statement text,
  culture_video_youtube_url character varying,
  culture_video_upload_path character varying,
  culture_video_type character varying CHECK (culture_video_type::text = ANY (ARRAY['youtube'::character varying, 'upload'::character varying]::text[])),
  is_published boolean DEFAULT false,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_by uuid,
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT companies_pkey PRIMARY KEY (id),
  CONSTRAINT companies_recruiter_id_fkey FOREIGN KEY (recruiter_id) REFERENCES auth.users(id),
  CONSTRAINT companies_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT companies_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.content_sections (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['about'::character varying, 'mission'::character varying, 'life'::character varying, 'perks'::character varying, 'team'::character varying, 'faqs'::character varying]::text[])),
  order_index integer NOT NULL,
  is_visible boolean DEFAULT true,
  title character varying,
  content text,
  image_urls jsonb DEFAULT '[]'::jsonb,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_by uuid,
  updated_at timestamp without time zone DEFAULT now(),
  deleted_at timestamp without time zone,
  CONSTRAINT content_sections_pkey PRIMARY KEY (id),
  CONSTRAINT content_sections_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT content_sections_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT content_sections_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.faqs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  question text NOT NULL,
  answer text NOT NULL,
  order_index integer NOT NULL,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_by uuid,
  updated_at timestamp without time zone DEFAULT now(),
  deleted_at timestamp without time zone,
  CONSTRAINT faqs_pkey PRIMARY KEY (id),
  CONSTRAINT faqs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT faqs_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT faqs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.jobs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  title character varying NOT NULL,
  description text NOT NULL,
  location character varying,
  job_type character varying DEFAULT 'full-time'::character varying CHECK (job_type::text = ANY (ARRAY['full-time'::character varying, 'part-time'::character varying, 'contract'::character varying, 'internship'::character varying]::text[])),
  salary_min numeric,
  salary_max numeric,
  salary_currency character varying,
  salary_period character varying CHECK (salary_period::text = ANY (ARRAY['monthly'::character varying, 'yearly'::character varying]::text[])),
  salary_range_string character varying,
  experience_level character varying DEFAULT 'mid'::character varying CHECK (experience_level::text = ANY (ARRAY['entry'::character varying, 'mid'::character varying, 'senior'::character varying]::text[])),
  status character varying DEFAULT 'open'::character varying CHECK (status::text = ANY (ARRAY['open'::character varying, 'closed'::character varying, 'draft'::character varying]::text[])),
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_by uuid,
  updated_at timestamp without time zone DEFAULT now(),
  deleted_at timestamp without time zone,
  is_featured boolean DEFAULT false,
  CONSTRAINT jobs_pkey PRIMARY KEY (id),
  CONSTRAINT jobs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT jobs_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT jobs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.video_uploads (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  file_name character varying NOT NULL,
  file_size integer,
  mime_type character varying CHECK (mime_type::text = ANY (ARRAY['video/mp4'::character varying, 'video/webm'::character varying, 'video/quicktime'::character varying]::text[])),
  storage_path character varying,
  duration integer,
  upload_status character varying DEFAULT 'completed'::character varying CHECK (upload_status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT video_uploads_pkey PRIMARY KEY (id),
  CONSTRAINT video_uploads_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);